name: The Skeld
world: the_skeld
emergencyMetting: 0.5, 99, 0.5
camera:
    loc: 12, 99, 30
    list:
    - -0.5, 101, 12.5, -6, 53
    - 17.5, 105, 42.5, -40, 77
    - 20.5, 102, 1.5, 180, 65
    - 14, 105, -35.5, 0, 55
spawns:
- 0.5, 98, 3.5
- 2.5, 98, 2.5
- 3.5, 98, 1.5
- 3.5, 98, -0.5
- 2.5, 98, -1.5
- 0.5, 98, -2.5
- -1.5, 98, -1.5
- -2.5, 98, -0.5
- -2.5, 98, 1.5
- -1.5, 98, 2.5
sabotage:
    reactor:
        locs:
        - 30, 99, 58
        - 7, 99, 57
        locTo: -17, 50, 20
        button1: -19, 51, 20
        button2: -21, 51, 20
    communicate:
        locs:
        - 50, 99, -11
        locTo: -17, 50, 10
        startBarInteract: -23, 50, 10
        endBarInteract: -23, 56, 10
        startBarTask: -23, 50, 12
        endBarTask: -23, 56, 12
    electrical:
        locs:
        - 32, 99, 22
        checkers:
        - -23, 53, 2
        - -23, 53, 0
        - -23, 53, -2
        - -23, 51, 2
        - -23, 51, 0
        - -23, 51, -2
        locTo: -17, 50, 0
    oxygen:
        locs:
        - 6, 99, -14
        - 21, 99, -18
        locTo: -17, 50, -10
        signEntered: -23, 51, -7
        signCode: -23, 51, -13
door:
    downDrive:
        locFrom:
        - 27, 98, 44
        - 37, 98, 32
        locTo:
        - 27, 101, 42
        - 35, 101, 32
    upDrive:
        locFrom:
        - 9, 98, 42
        - -1, 98, 32
        locTo:
        - 9, 101, 44
        - 1, 101, 32
    security:
        locFrom:
        - 19, 98, 36
        locTo:
        - 17, 101, 36
    medbay:
        locFrom:
        - 3, 98, 20
        locTo:
        - 3, 101, 18
    electrical:
        locFrom:
        - 39, 98, 20
        locTo:
        - 39, 101, 22
    cafeteria:
        locFrom:
        - 12, 98, -1
        - 1, 98, 12
        - -1, 98, -12
        locTo:
        - 12, 101, 1
        - -1, 101, 12
        - 1, 101, -12
    storage:
        locFrom:
        - 44, 98, 12
        - 27, 98, 1
        - 38, 98, -5
        locTo:
        - 42, 101, 12
        - 27, 101, -1
        - 40, 101, -5
manholes:
- 8.5, 98, -39.5 - 8.5, 94, -39.5
- 20.5, 98, -39.5 - 20.5, 94, -39.5
- 17.5, 98, -25.5 - 17.5, 94, -25.5
- 45.5, 98, -24.5 - 45.5, 94, -24.5
- 32.5, 98, -6.5 - 32.5, 94, -6.5
- 3.5, 98, -9.5 - 3.5, 94, -9.5
- -10.5, 98, -25.5 - -10.5, 94, -25.5
- 12.5, 98, 23.5 - 12.5, 94, 23.5
- 23.5, 98, 21.5 - 23.5, 94, 21.5
- 41.5, 98, 34.5 - 41.5, 94, 34.5
- -3.5, 98, 34.5 - -3.5, 94, 34.5
- 23.5, 98, 28.5 - 23.5, 94, 28.5
- 24.5, 98, 56.5 - 24.5, 94, 56.5
- 10.5, 98, 61.5 - 10.5, 94, 61.5
task:
    card:
        loc: 29, 98, -15
        locTo: 3, 50, 0
        startLoc: 1.5, 51, 2.5
        endLoc: 1.5, 51, -2.5
    meteor:
        loc: 0, 99, -25
        locTo: 3, 50, -10
        startPole: -3, 55, -8
        endPole: -3, 51, -12
    shipWay:
        loc: 9, 99, -46
        locTo: 3, 50, 10
        way:
        - -3, 52, 12
        - -3, 54, 10
        - -3, 52, 8
        - -3, 55, 7
    shield:
        loc: 45, 99, -19
        locTo: 3, 50, 20
        shields:
        - -3, 55, 20
        - -3, 54, 21
        - -3, 54, 19
        - -3, 53, 22
        - -3, 53, 20
        - -3, 53, 18
        - -3, 52, 21
        - -3, 52, 19
        - -3, 51, 20
    scan:
        loc: 14, 99, 16
        locTo: -7, 50, 0
        locScan: -10.5, 51, 0.5
        startBar: -13, 55, 3
        endBar: -13, 55, -3
    reactor:
        loc: 18, 99, 60
        locTo: -7, 50, -10
        barProgress:
        - -7, 55, -13
        - -7, 55, -11
        - -7, 55, -9
        - -7, 55, -7
        buttons:
        - -13, 55, -8
        - -13, 55, -10
        - -13, 55, -12
        - -13, 53, -8
        - -13, 53, -10
        - -13, 53, -12
        - -13, 51, -8
        - -13, 51, -10
        - -13, 51, -12
    calibrateDistr:
        loc: 23, 99, 11
        locTo: -27, 50, 20
        startPole: -33, 56, 23
        endPole: -33, 50, 17
    unlockManifold:
        loc: 8, 99, 61
        locTo: -27, 50, 10
        startPoleSign: -32, 52, 12
        endPoleSign: -32, 51, 8
    clearOxygen:
        loc: 7, 99, -13
        locTo: -37, 50, -10
        start: -43, 56, -8
        end: -43, 50, -13
    stabilizeWay:
        loc: 14, 99, -48
        locTo: -47, 50, 20
longTask:
    upload_download:
        nextStepsLoc:
        - -11, 99, -26
        - 8, 99, -43
        - 21, 99, -9
        - 44, 99, -9
        - 22, 99, 22
        nextStepsLocTo:
        - -7, 50, 20
        - -7, 50, 20
        - -7, 50, 20
        - -7, 50, 20
        - -7, 50, 20
        loc: -6, 99, -10
        locTo: -7, 50, 20
        startLocBarUpload: -12, 51, 17
        endLocBarUpload: -12, 51, 23
        startLocBarDownload: -12, 51, 17
        endLocBarDownload: -12, 51, 23
    rabbish:
        nextStepsLoc:
        - 48, 99, -3
        - 11, 99, -9
        nextStepsLocTo:
        - -7, 50, 10
        - -7, 50, 10
        loc: -7, 99, -10
        locTo: -7, 50, 10
        startLocRabbish: -13, 50, 8
        endLocRabbish: -11, 54, 12
        startLocGround: -11, 49, 12
        endLocGround: -13, 49, 8
    stabilize_drive:
        nextStepsLoc:
        - 5, 99, 45
        nextStepsLocTo:
        - -27, 50, 0
        loc: 39, 99, 45
        locTo: -27, 50, 0
        startLoc: -33, 56, 0
        endLoc: -33, 52, 0
    refuel:
        nextStepsLoc:
        - 4, 99, 44
        - 41, 98, 6
        - 38, 99, 44
        nextStepsLocTo:
        - -27, 50, -10
        - -27, 50, -10
        - -27, 50, -10
        loc: 41, 98, 6
        locTo: -27, 50, -10
        startLoc: -33, 50, -10
        endLoc: -33, 56, -10
    wires:
        nextStepsLoc:
        - 13, 99, -37
        - -8, 99, 8
        nextStepsLocTo:
        - -37, 50, 20
        - -37, 50, 20
        loc: 29, 99, 4
        locTo: -37, 50, 20
        wiresStart:
        - -43, 50, 22
        - -43, 56, 22
        - -43, 54, 22
        - -43, 52, 22
        wiresEnd:
        - -43, 50, 18
        - -43, 56, 18
        - -43, 54, 18
        - -43, 52, 18
    energy:
        nextStepsLoc:
        - 0, 99, -34
        - 10, 99, -21
        - 8, 99, -40
        - 31, 99, -32
        - 44, 99, -15
        - 29, 99, 45
        - -4, 99, 39
        - 13, 99, 29
        nextStepsLocTo:
        - -37, 50, 0
        - -37, 50, 0
        - -37, 50, 0
        - -37, 50, 0
        - -37, 50, 0
        - -37, 50, 0
        - -37, 50, 0
        - -37, 50, 0
        loc: 22, 99, 20
        locTo: -37, 50, 10
        startSlider: -43, 54, 10
        endSlider: -43, 56, 10
        button: -43, 53, 0
                